---
title: "Visualizing the Impact of The 2021 Polar Vortex Storm on Lighting in Texas"
author: "Stephan Kadonoff"
date: 11/11/2025
format: html
editor: visual
execute: 
  echo: true
  message: false
---

## Part 1 Preliminary Data Introduction

In this stage, we want to introduce the data relevant to the analysis.

```{r}
#read in relevant libraries
#| message: false
#| warning: false
library(terra) # raster handling
library(tidyverse)
library(here)
library(tmap) # map making
library(kableExtra) # table formatting
library(spData) # spatial data
library(spDataLarge) # spatial data
library(geodata) # spatial data
library(stars)
```

```{r}
# read in tiff files from the VIIRS data sets
VNP_1038_1 <- read_stars(here(
  "data", "VNP46A1", "VNP46A1.A2021038.h08v05.001.2021039064328.tif"
))
VNP_1038_2 <- read_stars(here(
  "data", "VNP46A1", "VNP46A1.A2021038.h08v06.001.2021039064329.tif"
))
VNP_1047_1 <- read_stars(here(
  "data", "VNP46A1", "VNP46A1.A2021047.h08v05.001.2021048091106.tif"
))
VNP_1047_2 <- read_stars(here(
  "data", "VNP46A1", "VNP46A1.A2021047.h08v06.001.2021048091105.tif"
))
plot(VNP_1038_1)
```

```{r}

```

```{r}
# utilize st_mosaic to merge same day files
VNP_1038 <- st_mosaic(VNP_1038_1, VNP_1038_2)
VNP_1047 <- st_mosaic(VNP_1047_1, VN__1047_2)

rm(test_merge)
plot(VNP_1047)
plot(VNP_1038)
```

```{r}
# find change in luminination by subtracting brightness value of 02-16 from 02-07
VNP_subtracted <- (VNP_1038 - VNP_1047)
plot(VNP_subtracted)
VNP_subtracted <- rast(VNP_subtracted)

rcl <- matrix(c(-Inf, 200, 0,
                200, Inf, 1),
              ncol = 3, byrow = TRUE)
vnp_reclassed <- classify(VNP_subtracted, rcl = rcl)
plot(vnp_reclassed)
```

```{r}
# create a mask of the above reclassified map
vnp_mask <- vnp_reclassed
vnp_mask[vnp_mask < 1] <- NA

# plot it
vnp_masked1 <- mask(vnp_reclassed, vnp_mask)
plot(vnp_masked1)

# set raster to vector
lumination_diff <- as.polygons(vnp_masked1) %>%
  st_as_sf() %>%
  st_make_valid()
plot(lumination_diff)
lumination_diff
```

```{r}
# bbox the above map
#c(-112.174228, 37.614998, -112.156230,37.629084)
houston_coords <- st_bbox(c(xmin = -96.5, xmax = -94.5, ymin = 29, ymax = 30.5), crs = st_crs(vnp_masked1)) %>%
  st_as_sfc
houston_coords
# wrap into st bbox
# st_crop instead of code below
```

```{r}
# texas zoom
houston_zoomed = st_bbox(c(xmin = -96.5, xmax = -94.5, ymin = 29, ymax = 30.5), crs = st_crs(vnp_masked1)) %>%
  st_as_sfc()

# crop to houston
houston_cropped <- st_crop(houston_coords, lumination_diff)
# update houston_cropped CRS to EPSG:3083
houston_cropped <-houston_cropped %>%
  st_transform(crs = 3083)
st_crs(houston_cropped)

```

## Part 2 Exclude highways from the cropped blackout mask

```{r}
# read in the highway data
road_data <- st_read((here("data", "gis_osm_roads_free_1.gpkg", "gis_osm_roads_free_1.gpkg")))

highway_data <- road_data %>%
  filter(fclass == "motorway")

# remove general road data
rm(road_dat)
# convert highway data to CRS 3083
highway_data <- highway_data %>%
  st_transform(crs = 3083)
# check units for st_buffer
st_crs(highway_data)$units

# create a buffer around the highways of 200 meters
highway_buffered <- st_buffer(highway_data, dist = 200)

#identify areas within 200 meters of all highways

highway_200m <- st_union(highway_buffered)
class(highway_200m)

# find the areas greater than 200 meter from all highways and keep it is as an sf data class
blackout_not_highway <- houston_cropped[lengths(st_intersects(houston_cropped, highway_200m)) == 0, ]

class(blackout_not_highway)

```

## Part 3 Identify the number of homes likely impacted by blackouts

```{r}
# read in building data 
building_data <- st_read(dsn = here("data", "gis_osm_buildings_a_free_1.gpkg", "gis_osm_buildings_a_free_1.gpkg"),
  query = "
    SELECT *
    FROM gis_osm_buildings_a_free_1
    WHERE (type IS NULL AND name IS NULL)
       OR type IN ('residential', 'apartments', 'house', 'static_caravan', 'detached')
  "
)

# change the crs of building_data
building_data <- building_data %>%
  st_transform(crs = 3083)

# transform blackout_not_highway to an sf object
blackout_not_highway <- st_sf(geometry = blackout_not_highway)

class(blackout_not_highway)

# join the buidling data with the non-highway black out data

blacked_out_buildings <- st_join(building_data, blackout_not_highway)


```

```{r}
# Example:
    gdb_path <- "path/to/your/geodatabase.gdb"
    layer_name <- "YourFeatureClassName" # Replace with the actual layer name

    # Read the feature class
    your_spatial_data <- st_read(dsn = gdb_path, layer = layer_name)
```

```{r}
st_layers("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb")
```

```{r}
# read in Census data
gdb_path <- "data/ACS_2019_5YR_TRACT_48_TEXAS.gdb"

layer_name <- "census_data"
st_layers("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb")

acs_geom <- st_read(dsn = "data/ACS_2019_5YR_TRACT_48_TEXAS.gdb",
                    layer = "ACS_2019_5YR_TRACT_48_TEXAS")

# stuff
acs_geom <- st_read("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb",
                    layer = "ACS_2019_5YR_TRACT_48_TEXAS")
acs_income <- st_read("data/ACS_2019_5YR_TRACT_48_TEXAS.gdb",
                      layer = "X19_INCOME")
acs_full <- acs_geom %>%
  left_join(acs_income, by = "GEOID")
plot(acs_full)
```

